### ISSUE TITLE
Kango doesn't support upcoming Firefox releases

### ISSUE THREAD

**Issue by iamolivinius** [secure-software-engineering/rose#126]
As of today there is no forseeable support in kango for upcoming Firefox releases.

I used Firefox nightly (42.0a) and installed the latest ROSE add on and a sample from the kango repository. _Both builds can not execute the content script_ 

FF follows a six week release cycle. FF42 will be released on Nov. 3rd '15. This issue can probably occure in earlier versions, too.  

This issue is also filed no kango's tracker.

**Comment by iamolivinius** [comment]
https://github.com/KangoExtensions/kango/issues/131#issuecomment-118684060

**Comment by iamolivinius** [comment]
Today, from kango dev team

    > Will this be in time for the official FF release date on Nov. 3rd?

    Sure, we will release new version before new Firefox release.

**Comment by dharma-guardian** [comment]
Rose is not working in Firefox 39.0 on OSX 10.10 due to an error in kango

**Comment by iamolivinius** [comment]
Which one?
Am 30.07.2015 7:51 nachm. schrieb "Felix" <notifications@github.com>:

**Comment by dharma-guardian** [comment]
EmberUI throws `TypeError: o is not a function kango_api.js:9:233`

Content script is not loaded

I did not debug the extension itself

**Comment by iamolivinius** [comment]
It's a kango issue. I just filed a report. Hope this is resolved soon. Until then there is no way to support FF.

**Comment by dharma-guardian** [comment]
Still the same error (https://github.com/secure-software-engineering/rose/issues/126#issuecomment-126591931) in Firefox 43.0.4 with Kango 1.8.

**Comment by apoller** [comment]
Okay, leave it at won't fix. We need to decide in the future whether we still maintain Firefox support, and use Kango or not.

**Comment by dharma-guardian** [comment]
#183
